name = "sofiasummit-events-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
PUBLIC_SITE_URL = "https://sofiasummit.bg"

[[d1_databases]]
binding = "DB"
database_name = "sofiasummit-events"
database_id = "59171d68-7a1e-492b-9014-1213ab3ffe5d"
