window.HRR_DATA = {
  "updatedAt": "2026-09-21",
  "teams": [
    {
      "rank": "1",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 31",
      "company": "Фикосота",
      "activity": "120",
      "mission": "22",
      "profiles": "4",
      "candidates": "255",
      "interviews": "12",
      "hired": "2",
      "total": "1605"
    },
    {
      "rank": "2",
      "city": "София",
      "university": "Университет по застраховане и финанси (УЗФ)",
      "team": "Екип 1",
      "company": "Вива Кредит",
      "activity": "40",
      "mission": "10",
      "profiles": "0",
      "candidates": "183",
      "interviews": "7",
      "hired": "1",
      "total": "1065"
    },
    {
      "rank": "3",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 12",
      "company": "Либхер",
      "activity": "110",
      "mission": "22",
      "profiles": "7",
      "candidates": "114",
      "interviews": "4",
      "hired": "1",
      "total": "786"
    },
    {
      "rank": "4",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 7",
      "company": "C team",
      "activity": "200",
      "mission": "13",
      "profiles": "5",
      "candidates": "52",
      "interviews": "2",
      "hired": "1",
      "total": "533"
    },
    {
      "rank": "5",
      "city": "София",
      "university": "Университетът за национално и световно стопанство (УНСС)",
      "team": "Екип 11",
      "company": "Вива Кредит",
      "activity": "100",
      "mission": "22",
      "profiles": "5",
      "candidates": "42",
      "interviews": "6",
      "hired": "1",
      "total": "432"
    },
    {
      "rank": "6",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 9",
      "company": "C team",
      "activity": "80",
      "mission": "13",
      "profiles": "6",
      "candidates": "51",
      "interviews": "2",
      "hired": "1",
      "total": "410"
    },
    {
      "rank": "7",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 9",
      "company": "D&D Doors",
      "activity": "50",
      "mission": "22",
      "profiles": "4",
      "candidates": "26",
      "interviews": "3",
      "hired": "1",
      "total": "270"
    },
    {
      "rank": "8",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 2",
      "company": "Лидл",
      "activity": "60",
      "mission": "4",
      "profiles": "9",
      "candidates": "33",
      "interviews": "2",
      "hired": "0",
      "total": "267"
    },
    {
      "rank": "9",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 2",
      "company": "Адрес",
      "activity": "60",
      "mission": "22",
      "profiles": "8",
      "candidates": "16",
      "interviews": "2",
      "hired": "0",
      "total": "198"
    },
    {
      "rank": "10",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 9",
      "company": "Кауфланд",
      "activity": "50",
      "mission": "22",
      "profiles": "2",
      "candidates": "23",
      "interviews": "0",
      "hired": "0",
      "total": "191"
    },
    {
      "rank": "11",
      "city": "София",
      "university": "Университетът за национално и световно стопанство (УНСС)",
      "team": "Екип 17",
      "company": "Примо +",
      "activity": "50",
      "mission": "13",
      "profiles": "6",
      "candidates": "17",
      "interviews": "2",
      "hired": "0",
      "total": "180"
    },
    {
      "rank": "12",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 1",
      "company": "Латекоер",
      "activity": "10",
      "mission": "4",
      "profiles": "0",
      "candidates": "16",
      "interviews": "0",
      "hired": "0",
      "total": "94"
    },
    {
      "rank": "13",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 15",
      "company": "БТЛ",
      "activity": "20",
      "mission": "4",
      "profiles": "0",
      "candidates": "9",
      "interviews": "2",
      "hired": "0",
      "total": "89"
    },
    {
      "rank": "14",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 6",
      "company": "Примо +",
      "activity": "25",
      "mission": "22",
      "profiles": "1",
      "candidates": "6",
      "interviews": "0",
      "hired": "0",
      "total": "79"
    },
    {
      "rank": "15",
      "city": "Пловдив",
      "university": "ПУ - ТУ",
      "team": "Екип 21",
      "company": "Латекоер",
      "activity": "20",
      "mission": "2",
      "profiles": "0",
      "candidates": "8",
      "interviews": "0",
      "hired": "0",
      "total": "62"
    },
    {
      "rank": "16",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 13",
      "company": "БТЛ",
      "activity": "20",
      "mission": "4",
      "profiles": "0",
      "candidates": "6",
      "interviews": "0",
      "hired": "0",
      "total": "54"
    },
    {
      "rank": "17",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 10",
      "company": "Неопърл",
      "activity": "30",
      "mission": "21",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "51"
    },
    {
      "rank": "18",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 13 / Екип 14",
      "company": "ДТМ / Фикосота",
      "activity": "29",
      "mission": "4",
      "profiles": "0",
      "candidates": "2",
      "interviews": "0",
      "hired": "0",
      "total": "43"
    },
    {
      "rank": "19",
      "city": "София",
      "university": "Университет по библиотекознание и информационни технологии (УниБИТ)",
      "team": "Екип 7",
      "company": "Лидл",
      "activity": "10",
      "mission": "4",
      "profiles": "0",
      "candidates": "5",
      "interviews": "0",
      "hired": "0",
      "total": "39"
    },
    {
      "rank": "20",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 18",
      "company": "C team",
      "activity": "20",
      "mission": "10",
      "profiles": "0",
      "candidates": "1",
      "interviews": "0",
      "hired": "0",
      "total": "35"
    },
    {
      "rank": "21",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 24",
      "company": "ActionCOACH",
      "activity": "25",
      "mission": "4",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "29"
    },
    {
      "rank": "22",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 2",
      "company": "БТЛ",
      "activity": "20",
      "mission": "4",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "24"
    },
    {
      "rank": "23",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 8",
      "company": "Pleggi",
      "activity": "15",
      "mission": "4",
      "profiles": "0",
      "candidates": "1",
      "interviews": "0",
      "hired": "0",
      "total": "24"
    },
    {
      "rank": "24",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 12",
      "company": "ActionCOACH",
      "activity": "10",
      "mission": "4",
      "profiles": "1",
      "candidates": "1",
      "interviews": "0",
      "hired": "0",
      "total": "21"
    },
    {
      "rank": "25",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 7",
      "company": "Фикосота",
      "activity": "16",
      "mission": "4",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "20"
    },
    {
      "rank": "26",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 16",
      "company": "New career",
      "activity": "13",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "15"
    },
    {
      "rank": "27",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 5",
      "company": "Фикосота",
      "activity": "13",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "15"
    },
    {
      "rank": "28",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 19",
      "company": "Payslip",
      "activity": "10",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "12"
    },
    {
      "rank": "29",
      "city": "София",
      "university": "Софийски университет „Свети Климент Охридски“",
      "team": "Екип 3",
      "company": "Фикосота",
      "activity": "8",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "10"
    },
    {
      "rank": "30",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 13",
      "company": "Адрес",
      "activity": "5",
      "mission": "4",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "9"
    },
    {
      "rank": "31",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 3",
      "company": "Кауфланд",
      "activity": "6",
      "mission": "1",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "7"
    },
    {
      "rank": "32",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 4",
      "company": "Спортал",
      "activity": "5",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "7"
    },
    {
      "rank": "33",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 5",
      "company": "New career",
      "activity": "6",
      "mission": "1",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "7"
    },
    {
      "rank": "34",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 8",
      "company": "Либхер",
      "activity": "6",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "6"
    },
    {
      "rank": "35",
      "city": "Пловдив",
      "university": "ТУ - Пловдив",
      "team": "Екип 10",
      "company": "Кауфланд",
      "activity": "4",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "6"
    },
    {
      "rank": "36",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 19",
      "company": "Латекоер",
      "activity": "1",
      "mission": "4",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "5"
    },
    {
      "rank": "37",
      "city": "София",
      "university": "Университетът за национално и световно стопанство (УНСС)",
      "team": "Екип 12",
      "company": "Примо +",
      "activity": "1",
      "mission": "2",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "3"
    },
    {
      "rank": "38",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 17",
      "company": "Лидл",
      "activity": "1",
      "mission": "1",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "2"
    },
    {
      "rank": "39",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 14",
      "company": "Адрес",
      "activity": "1",
      "mission": "1",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "2"
    },
    {
      "rank": "40",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 10",
      "company": "BDO",
      "activity": "1",
      "mission": "1",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "2"
    },
    {
      "rank": "41",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 4",
      "company": "Фикосота",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "42",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 6",
      "company": "Лидл",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "43",
      "city": "Пловдив",
      "university": "ПУ",
      "team": "Екип 11",
      "company": "Фикосота",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "44",
      "city": "Пловдив",
      "university": "УХТ",
      "team": "Екип 20",
      "company": "Адрес",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "45",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 5",
      "company": "BDO",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "46",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 8",
      "company": "Кауфланд",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "47",
      "city": "София",
      "university": "Университетът за национално и световно стопанство (УНСС)",
      "team": "Екип 15",
      "company": "Спортал",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "48",
      "city": "София",
      "university": "Нов български университет",
      "team": "Екип 16",
      "company": "ДТМ",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "49",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 1",
      "company": "Pleggi",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "50",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 3",
      "company": "Лидл",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "51",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 4",
      "company": "Payslip",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "52",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 6",
      "company": "Лидл",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "53",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 11",
      "company": "D&D Doors",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "54",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 14",
      "company": "Кауфланд",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "55",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 15",
      "company": "D&D Doors",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "56",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 16",
      "company": "Лидл",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "57",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 17",
      "company": "БИНК",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "58",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 18",
      "company": "ActionCOACH",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "59",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 20",
      "company": "БИНК",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "60",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 21",
      "company": "Неопърл",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "61",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 22",
      "company": "Фикосота",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "62",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 23",
      "company": "Pleggi",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "63",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 25",
      "company": "БДО",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "64",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 26",
      "company": "БИНК",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "65",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 27",
      "company": "Кауфланд",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "66",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 28",
      "company": "БДО",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "67",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 29",
      "company": "Кауфланд",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "68",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 30",
      "company": "Payslip",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "69",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 32",
      "company": "Адрес",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "70",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 33",
      "company": "Payslip",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    },
    {
      "rank": "71",
      "city": "Варна",
      "university": "ИУВ",
      "team": "Екип 34",
      "company": "Pleggi",
      "activity": "0",
      "mission": "0",
      "profiles": "0",
      "candidates": "0",
      "interviews": "0",
      "hired": "0",
      "total": "0"
    }
  ],
  "missions": [
    {
      "order": "0",
      "title": "Стартъп изложението в УниБИТ на 13.11 от 10:00ч.",
      "owner": "Цецо",
      "deadline": "само на датата",
      "reward": "НЯМА",
      "points": "5",
      "note": "Искам качена снимка с тагване и доказателство"
    },
    {
      "order": "1",
      "title": "Pleggi профил",
      "owner": "Цецо",
      "deadline": "3 дни",
      "reward": "НЯМА",
      "points": "1",
      "note": "Профила се качва в коментар на мисията"
    },
    {
      "order": "2",
      "title": "LinkedIn профил",
      "owner": "Цецо",
      "deadline": "3 дни",
      "reward": "НЯМА",
      "points": "1",
      "note": "Профила се качва в коментар на мисията"
    },
    {
      "order": "3",
      "title": "Публикация HR:Rush for Practice",
      "owner": "Христо",
      "deadline": "10 дни ",
      "reward": "НЯМА",
      "points": "3",
      "note": "След публикуване в 3 канала (FB, LI, Instagram)"
    },
    {
      "order": "4",
      "title": "Влез в обувките/ Подготовка за среща",
      "owner": "Вики Д",
      "deadline": "",
      "reward": "Консулт. с Вики",
      "points": "5",
      "note": "След изпращане на имейл или ЛС на профил на кандидата "
    },
    {
      "order": "5",
      "title": "Таблица на всичко",
      "owner": "Тошко",
      "deadline": "",
      "reward": "НЯМА",
      "points": "20",
      "note": ""
    },
    {
      "order": "Извънредна",
      "title": "Безплатен уебинар - Емануел Тонев",
      "owner": "Емо",
      "deadline": "само на датата",
      "reward": "НЯМА",
      "points": "3",
      "note": "Емо казва присъстващи"
    },
    {
      "order": "6",
      "title": "Среща с екипите - конкуренти",
      "owner": "Надя",
      "deadline": "10 дни ",
      "reward": "НЯМА",
      "points": "4",
      "note": "по 2 т. на човек от екип при изпълние на условията"
    },
    {
      "order": "7",
      "title": "Намери 5 кандидата по позицията в Pleggi",
      "owner": "Цецо",
      "deadline": "5 дни",
      "reward": "НЯМА",
      "points": "50",
      "note": ""
    },
    {
      "order": "8",
      "title": "Меме",
      "owner": "Сашо",
      "deadline": "3 дни",
      "reward": "Сашо ще качи мемето",
      "points": "5",
      "note": "5 т. само на победителя"
    },
    {
      "order": "9",
      "title": "Направи видео, с което да кандидатсват хората за позицията ви.",
      "owner": "Красен",
      "deadline": "7 дни",
      "reward": "Обучение от мен",
      "points": "5",
      "note": "Публикуване в социална мрежа по избор и тагване на HR: Rush For Pracitce. "
    },
    {
      "order": "10",
      "title": "Направи 12 асистенции / намерени кандидати за всяка друга комапния (освен твоята)",
      "owner": "Цецо",
      "deadline": "5 дни",
      "reward": "НЯМА",
      "points": "20",
      "note": "20 точки отделно от точките за кандидатите, ако мисията е в срок"
    },
    {
      "order": "15",
      "title": "Посети една лекция/ упражнение в университета и продавай позиция",
      "owner": "Цецо",
      "deadline": "10 дни",
      "reward": "НЯМА",
      "points": "5",
      "note": "Искам качена снимка с тагване и доказателство"
    },
    {
      "order": "7",
      "title": "“Откривател на позиции”",
      "owner": "Бранко",
      "deadline": "",
      "reward": "НЯМА",
      "points": "",
      "note": ""
    },
    {
      "order": "11",
      "title": "Интервюта с ментори",
      "owner": "Вики Л",
      "deadline": "",
      "reward": "НЯМА",
      "points": "8",
      "note": ""
    },
    {
      "order": "12",
      "title": "Живо обучение за презентиращи",
      "owner": "Вики/Илияна/Надя/Вики/Емо",
      "deadline": "",
      "reward": "НЯМА",
      "points": "5",
      "note": ""
    }
  ]
};
